### ISSUE TITLE
Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

### ISSUE THREAD

**Issue by koyamakkkkk** [comfyanonymous/ComfyUI_TensorRT#21]
when using this node, error happens

Error occurred when executing STATIC_TRT_MODEL_CONVERSION:

Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

File "/home/ubuntu/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/ubuntu/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/ubuntu/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_TensorRT/tensorrt_convert.py", line 598, in convert
return super()._convert(
File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_TensorRT/tensorrt_convert.py", line 257, in _convert
torch.onnx.export(
File "/opt/tensorflow/lib/python3.10/site-packages/torch/onnx/utils.py", line 506, in export
_export(
File "/opt/tensorflow/lib/python3.10/site-packages/torch/onnx/utils.py", line 1548, in _export
graph, params_dict, torch_out = _model_to_graph(
File "/opt/tensorflow/lib/python3.10/site-packages/torch/onnx/utils.py", line 1117, in _model_to_graph
graph = _optimize_graph(
File "/opt/tensorflow/lib/python3.10/site-packages/torch/onnx/utils.py", line 665, in _optimize_graph
graph = _C._jit_pass_onnx(graph, operator_export_type)
File "/opt/tensorflow/lib/python3.10/site-packages/torch/onnx/utils.py", line 1901, in _run_symbolic_function
raise errors.UnsupportedOperatorError(
<img width="1101" alt="スクリーンショット 2024-06-09 14 58 33" src="https://github.com/comfyanonymous/ComfyUI_TensorRT/assets/109265714/1ed05cf1-1f2c-453d-96ac-fe1f6de4f5d6">

**Comment by RONNYKHALIL** [comment]
+1

**Comment by comfyanonymous** [comment]
You have to update pytorch.

**Comment by ech3lon42** [comment]
Currently getting a very similar error when compiling the static model.

`Error occurred when executing STATIC_TRT_MODEL_CONVERSION:

Exporting the operator 'aten::fft_fftn' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

  File "I:\StableDiffusion\ComfyNew\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\StableDiffusion\ComfyNew\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\StableDiffusion\ComfyNew\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\StableDiffusion\ComfyNew\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\StableDiffusion\ComfyNew\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TensorRT\tensorrt_convert.py", line 605, in convert
    return super()._convert(
           ^^^^^^^^^^^^^^^^^
  File "I:\StableDiffusion\ComfyNew\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TensorRT\tensorrt_convert.py", line 264, in _convert
    torch.onnx.export(
  File "I:\StableDiffusion\ComfyNew\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\utils.py", line 516, in export
    _export(
  File "I:\StableDiffusion\ComfyNew\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\utils.py", line 1612, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "I:\StableDiffusion\ComfyNew\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\utils.py", line 1138, in _model_to_graph
    graph = _optimize_graph(
            ^^^^^^^^^^^^^^^^
  File "I:\StableDiffusion\ComfyNew\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\utils.py", line 677, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\StableDiffusion\ComfyNew\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\utils.py", line 1966, in _run_symbolic_function
    raise errors.UnsupportedOperatorError`

Is there anything wrong with my requirements?

torch==2.3.0+cu121
torchaudio==2.3.0+cu121
torchdiffeq==0.2.3
torchmetrics==0.2.0
torchvision==0.18.0+cu121
xformers==0.0.26.post1
tensorrt==10.1.0
onnx==1.16.1
onnxruntime==1.18.0
onnxruntime-gpu==1.18.0

**Comment by theryex** [comment]
I have the same issue.
!!! Exception during processing!!! Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
Traceback (most recent call last):
  File "L:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "L:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "L:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "L:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TensorRT\tensorrt_convert.py", line 611, in convert
    return super()._convert(
  File "L:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TensorRT\tensorrt_convert.py", line 270, in _convert
    torch.onnx.export(
  File "L:\ComfyUI\python_embeded\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "L:\ComfyUI\python_embeded\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "L:\ComfyUI\python_embeded\lib\site-packages\torch\onnx\utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "L:\ComfyUI\python_embeded\lib\site-packages\torch\onnx\utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "L:\ComfyUI\python_embeded\lib\site-packages\torch\onnx\utils.py", line 1901, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.


Not using FreeU or anything other than model loader to TRT.

**Comment by ragnarok00732** [comment]
!!! Exception during processing !!! Exporting the operator 'aten::copy' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub:
https://github.com/pytorch/pytorch/issues.
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TensorRT\tensorrt_convert.py", line 539, in convert
    return super()._convert(
           ^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TensorRT\tensorrt_convert.py", line 282, in _convert
    torch.onnx.export(
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\onnx\utils.py", line 557, in export
    _export(
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\onnx\utils.py", line 1621, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\onnx\utils.py", line 1172, in _model_to_graph
    graph = _optimize_graph(
            ^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\onnx\utils.py", line 694, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\onnx\utils.py", line 1913, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::copy' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub:
https://github.com/pytorch/pytorch/issues.

This issue it's just so annoying guys, I've just updated everything included: onnx,comfyui,torch, but nothing. It doesn't work.

**Comment by jelling** [comment]
Same issue here even with pytorch 2.4.0.
