### ISSUE TITLE
[Bug] RuntimeError: The size of tensor a (96) must match the size of tensor b (168) at non-singleton dimension 3

### ISSUE THREAD

**Issue by yusing** [comfyanonymous/ComfyUI_TensorRT#29]
### Environment:

- OS: Windows 11 24H2 26100.712
- Python: 3.10.11
- Pytorch: 2.3.1+cu121

### What I have tried:

- [Create_SD1.5_TRT_Dynamic.json](https://github.com/comfyanonymous/ComfyUI_TensorRT/blob/master/workflows/Create_SD1.5_TRT_Dynamic.json)
- [Create_SDXL_Base_TT_Static.json](https://github.com/comfyanonymous/ComfyUI_TensorRT/blob/master/workflows/Create_SDXL_Base_TT_Static.json)

### Which node triggered the error:

KSampler

### Complete log output:

```shell
C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
Requested to load SDXL
Loading 1 new model
C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py:655: UserWarning: backend:cudaMallocAsync ignores max_split_size_mb,roundup_power2_divisions, and garbage_collect_threshold. (Triggered internally at ..\c10\cuda\CUDAAllocatorConfig.cpp:311.)
  if latent_image is not None and torch.count_nonzero(latent_image) > 0: #Don't shift the empty latent image.
  0%|          | 0/50 [00:00<?, ?it/s][06/16/2024-09:48:39] [TRT] [E] IExecutionContext::setInputShape: Error Code 3: API Usage Error (Parameter check failed, condition: engineDims.d[i] == dims.d[i]. Static dimension mismatch while setting input shape for x. Set dimensions are [1,4,168,96]. Expected dimensions are [1,4,96,168].)
  0%|          | 0/50 [00:00<?, ?it/s]
!!! Exception during processing!!! The size of tensor a (96) must match the size of tensor b (168) at non-singleton dimension 3
Traceback (most recent call last):
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\nodes.py", line 1358, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\nodes.py", line 1328, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 313, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control_reference.py", line 47, in refcn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 111, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 794, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 696, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 683, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 662, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 567, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\k_diffusion\sampling.py", line 142, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 291, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 649, in __call__
    return self.predict_noise(*args, **kwargs)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 652, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 277, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 226, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 63, in apply_model_uncond_cleanup_wrapper
    return orig_apply_model(self, *args, **kwargs)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_base.py", line 114, in apply_model
    return self.model_sampling.calculate_denoised(sigma, model_output, x)
  File "C:\Projects\OpenSource\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_sampling.py", line 12, in calculate_denoised
    return model_input - model_output * sigma
RuntimeError: The size of tensor a (96) must match the size of tensor b (168) at non-singleton dimension 3

Prompt executed in 15.23 seconds

```

**Comment by yusing** [comment]
Oh it's me entering wrong width and height, nvm
