### ISSUE TITLE
Can't convert SDXL models 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported

### ISSUE THREAD

**Issue by NeoLoger** [comfyanonymous/ComfyUI_TensorRT#8]
Whenever I try to convert an SDXL model, any model I try I get the same error. 
`Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported`

Here are my config, its jut a model and the Dynamic model converter.
![image](https://github.com/comfyanonymous/ComfyUI_TensorRT/assets/23522883/480fb205-d903-4d61-81d0-0596202c6700)

![image](https://github.com/comfyanonymous/ComfyUI_TensorRT/assets/23522883/cb06e73a-2031-40eb-aec0-ac62296aa12f)

```
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load SDXL
Loading 1 new model
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
None
<Set verbose=True to see more details>


!!! Exception during processing!!! Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
Traceback (most recent call last):
  File "A:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "A:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "A:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TensorRT\tensorrt_convert.py", line 510, in convert
    return super()._convert(
  File "A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TensorRT\tensorrt_convert.py", line 257, in _convert
    torch.onnx.export(
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\onnx\utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\onnx\utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\onnx\utils.py", line 1901, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
```

Am I missing something?
Do I need to install something?

**Comment by comfyanonymous** [comment]
Update your pytorch version to the latest stable one.
