### ISSUE TITLE
A bytes-like object is required ...

### ISSUE THREAD

**Issue by Torcelllo** [comfyanonymous/ComfyUI_TensorRT#88]
... not None Type.

![TRT-DYN Auraflow3](https://github.com/user-attachments/assets/65b7fc8b-5cbf-4dc4-b86c-26dc68b3cc84)

![TensorRT](https://github.com/user-attachments/assets/b4bf9b06-aa89-49d7-a484-a55fdcbe3cdb)

!!! Exception during processing !!! a bytes-like object is required, not 'NoneType'
Traceback (most recent call last):
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TensorRT\tensorrt_convert.py", line 539, in convert
    return super()._convert(
           ^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TensorRT\tensorrt_convert.py", line 384, in _convert
    f.write(serialized_engine)
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by Haoming02** [comment]
Your `context_max` is way too large

Each "`1`" context means 75 tokens
